---
language: ruby
sudo: false
bundler_args: --without development
script: "rake spec"
matrix:
  fast_finish: true
  include:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.7.0" ONLY_OS=centos-7-x86_64 FUTURE_PARSER=yes TRUSTED_NODE_DATA=yes
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.7.0" ONLY_OS=centos-7-x86_64
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 4.7.0" ONLY_OS=centos-7-x86_64
